### ISSUE TITLE
Inference time question about caching

### ISSUE THREAD

**Issue by SangbumChoi** [allenai/EmbeddingRecycling#4]
Hi, I have question of Table 3 which is average inference runtime comparison.

I understand that theoritical speedup is 100% because it has been freezed for 50% of layer.
However, what I don't understand is that
Recycling should be A+B 
(A:generating feature from initial transformer, same as caching data)
(B:loading cached data, and do some later transformer calculation)
But I think your paper compared with B.
Does my understanding is right?
If it isn't how can A+B is much more smaller than regular? Did you used some kind of parallelism method?

Thanks

**Comment by dcdowney** [comment]
@SangbumChoi I apologize for the late response and thanks for your interest.  In case the answer is still helpful: the final [paper](https://api.semanticscholar.org/CorpusID:250425903) explains this better.  For inference (Table 4) we measure speedup assuming the cache is already populated.  For training (Table 5), we compare the setting where the cache is pre-populated to one where it isn't and needs to be generated in the first of six training epochs.
